---
linters:
  disable-all: true
  enable:
  - asciicheck
  - bidichk
  - deadcode
  - durationcheck
  - exhaustive
  - errcheck
  - errorlint
  - exportloopref
  - gochecknoinits
  - goconst
  - gocritic
  - gofmt
  - gosec
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - nilerr
  - nolintlint
  - revive
  - sqlclosecheck
  - staticcheck
  - structcheck
  - typecheck
  - unparam
  - unused
  - varcheck
  - wastedassign
  - whitespace
  - wrapcheck
issues:
  include:
  # Reenable some checks golangci-lint disables by default (see golangci-lint run --help)
  - EXC0001
  - EXC0004
  - EXC0005
  - EXC0006
  - EXC0007
linters-settings:
  errcheck:
    ignore: "" # Disable the overbroad ignore rules (they ignore things like Fprintf)
