package git

import (
	"bufio"
	"fmt"
	"strings"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
)

type Patch struct {
	Lines []PatchLine
}

type PatchLine struct {
	// ALineNum is the line number from the a (old) file. Will be null if the
	// line does not represent a line from the a file (ie: metadata or b).
	ALineNum *int
	// BLineNum is the line number from the b (new) file. Will be null if the
	// line does not represent a line from the b file (ie: metadata or a).
	BLineNum *int
	// Meta is the Hunk metadata and is a pointer for efficiency rather than
	// for editability.
	Meta *HunkMeta
	// Text is the raw text from the patch file generated by the git diff.
	Text string
}

type HunkMeta struct {
	AFile string
	AHash string
	AMode string
	BFile string
	BHash string
	BMode string
}

func Diff(repoDir, base, head string) (string, error) {
	repo, err := git.PlainOpen(repoDir)
	if err != nil {
		return "", fmt.Errorf("git open: %w", err)
	}
	baseCommit, err := repo.CommitObject(plumbing.NewHash(base))
	if err != nil {
		return "", fmt.Errorf("git base commit: %w", err)
	}
	baseTree, err := baseCommit.Tree()
	if err != nil {
		return "", fmt.Errorf("git base tree: %w", err)
	}
	headCommit, err := repo.CommitObject(plumbing.NewHash(head))
	if err != nil {
		return "", fmt.Errorf("git head commit: %w", err)
	}
	headTree, err := headCommit.Tree()
	if err != nil {
		return "", fmt.Errorf("git head tree: %w", err)
	}
	patch, err := baseTree.Patch(headTree)
	if err != nil {
		return "", fmt.Errorf("git diff: %w", err)
	}
	return patch.String(), nil
}

// ParseDiff parses a resultant diff to allow for mapping from
func ParseDiff(diff string) Patch {
	var prefixed strings.Builder
	scanner := bufio.NewScanner(strings.NewReader(diff))
	for i := 0; scanner.Scan(); i++ {
		line := scanner.Text()
		prefixed.WriteString(fmt.Sprintf("%d: %s\n", i, line))
	}
	return Patch{}
}

func PrefixDiff(diff string) string {
	var prefixed strings.Builder
	scanner := bufio.NewScanner(strings.NewReader(diff))
	for i := 0; scanner.Scan(); i++ {
		line := scanner.Text()
		prefixed.WriteString(fmt.Sprintf("Line %d: %s\n", i, line))
	}
	return prefixed.String()
}
